services:
  postgres:
    image: postgres:17-alpine
    container_name: global-payment-postgres
    environment:
      POSTGRES_DB: global_payment_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5732:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
