-- Schema for the Global Payment Service. Written to run identically against real Postgres
-- (docker-compose, prod) and H2 in PostgreSQL-compatibility mode (tests, see
-- src/test/resources/application.properties) — no Postgres-only syntax (e.g. `gen_random_uuid()`,
-- `timestamptz`, jsonb) so the same migration is what both environments actually run, instead of
-- tests exercising a Hibernate-autogenerated schema that could silently drift from this one.
--
-- Primary keys are generated in application code (Hibernate's UUID generator), not by a database
-- default expression, so nothing here depends on either engine's UUID-generation function.

create table account (
    id         uuid not null primary key,
    owner_name varchar(255) not null,
    currency   varchar(3) not null,
    balance    numeric(19, 4) not null,
    version    bigint not null default 0
);

create table transfer (
    id              uuid not null primary key,
    idempotency_key varchar(255) not null,
    from_account_id uuid not null references account (id),
    to_account_id   uuid not null references account (id),
    amount          numeric(19, 4) not null,
    source_currency varchar(3) not null,
    target_currency varchar(3) not null,
    exchange_rate   numeric(19, 8),
    status          varchar(20) not null,
    notified_at     timestamp with time zone,
    created_at      timestamp with time zone not null default current_timestamp
);

create unique index ux_transfer_idempotency_key on transfer (idempotency_key);
create index ix_transfer_from_account on transfer (from_account_id);
create index ix_transfer_to_account on transfer (to_account_id);
-- plain composite index, not a partial/filtered one (`where notified_at is null`) — H2 doesn't
-- support filtered indexes even in PostgreSQL mode, and this shape matches the publisher's
-- actual query (`where status = 'COMPLETED' and notified_at is null`, see server README §7)
-- at least as well as a filtered index on created_at would have
create index ix_transfer_pending_notification on transfer (status, notified_at);
